FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p uploads data temp

EXPOSE 5001

CMD flask db init || true && \
    flask db migrate -m "Initial migration" || true && \
    flask db upgrade || true && \
    python run.py 